namespace UFE3D
{
    public enum BodyPart
    {
        none,
        head,
        upperTorso,
        lowerTorso,
        leftUpperArm,
        rightUpperArm,
        leftForearm,
        rightForearm,
        leftHand,
        rightHand,
        leftThigh,
        rightThigh,
        leftCalf,
        rightCalf,
        leftFoot,
        rightFoot,
        root,
        custom1,
        custom2,
        custom3,
        custom4,
        custom5,
        custom6,
        custom7,
        custom8,
        custom9
    }
}